version: '3.8'

services:
  product-service:
    image: product-service
    container_name: product-service-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      MYSQL_URL: jdbc:mysql://mysql:3306/product_service_db
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
    networks:
      - my-network
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: product_service_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my-network

volumes:
  mysql_data:

networks:
  my-network:
    driver: bridge